<!-- STYLE -->
<link href="https://fonts.googleapis.com/css?family=Poppins:100,300,500" rel="stylesheet">
<!-- CSS -->
<link rel="stylesheet" href="/home/css/linearicons.css">
<link rel="stylesheet" href="/home/css/owl.carousel.css">
<link rel="stylesheet" href="/home/css/font-awesome.min.css">
<link rel="stylesheet" href="/home/css/nice-select.css">
<link rel="stylesheet" href="/home/css/magnific-popup.css">
<link rel="stylesheet" href="/home/css/bootstrap.css">
<link rel="stylesheet" href="/home/css/main.css">
<!-- STYLE -->