<!--  JS  -->
{!! Html::script('/admin/js/jquery-3.2.1.min.js') !!}
{!! Html::script('/admin/js/bootstrap.min.js') !!}
{!! Html::script('/admin/js/material.min.js') !!}
{!! Html::script('/admin/js/chartist.min.js') !!}
{!! Html::script('/admin/js/arrive.min.js') !!}
{!! Html::script('/admin/js/perfect-scrollbar.jquery.min.js') !!}
{!! Html::script('/admin/js/bootstrap-notify.js') !!}
{!! Html::script('/admin/js/material-dashboard.js?v=1.2.0') !!}
{!! Html::script('/admin/js/init.js') !!}
{!! Html::script('https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.16/js/jquery.dataTables.min.js') !!}
